using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;

namespace CrossbowDamageMultiplier;

public class Program
{
    private static Lazy<Settings> _settings = null!;
    private static Settings Settings => _settings.Value;
    
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
            .Run(args);
    }

    private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? _state;
    internal static IPatcherState<ISkyrimMod, ISkyrimModGetter> State => _state!;

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        _state = state;
        var blacklistedIDs = string.Join(",", Settings.Blacklist).Split(",").ToList();
        foreach (var weaponGetter in state.LoadOrder.PriorityOrder.Weapon().WinningContextOverrides())
        {
            var weapon = weaponGetter.Record;
            if (weapon.EditorID == null || !weapon.EditorID.ContainsInsensitive("Crossbow"))
                continue;

            var contexts = state.LinkCache.ResolveAllContexts<IWeapon, IWeaponGetter>(weapon.FormKey).ToList();
            var originalMod = contexts[^1].ModKey;
            if (ShouldSkip(originalMod, weapon, blacklistedIDs))
            {
                Console.WriteLine("Skipping " + weapon.EditorID + " from mod " + originalMod);
                continue;
            }

            IWeapon modifiedEffect = weaponGetter.GetOrAddAsOverride(state.PatchMod);
            var originalDamage = modifiedEffect.BasicStats?.Damage;
            if (originalDamage is null or <= 0)
                continue;
                    
            var newDamage = (ushort)(originalDamage.Value * Settings.DamageMultiplier);
            modifiedEffect.BasicStats!.Damage = newDamage;
            Console.WriteLine($"Crossbow: {weapon.EditorID} Damage changed from {originalDamage} to {newDamage}");
        }
    }

    private static bool ShouldSkip(ModKey originalMod, IMajorRecordGetter record, IEnumerable<string> blacklistedIDs)
        => Settings.IgnoredMods.Contains(originalMod)
            || record.EditorID == null
            || blacklistedIDs.Any(record.EditorID.HasValueAndContainsId);
}